import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Navbar from "../../components/Navbar";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>VIROR | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/leaf.png" />
      </Head>
      <Navbar/>
      <div className={styles.body}>
        <h1 className={styles.heading}>This is the Home page</h1>
        <p className={styles.para}>text</p>
        
      </div>
      
    </>
  );
}
