import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Navbar from "../../components/Navbar";
import Image from "next/image";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>VIROR | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/leaf.png" />
      </Head>
      <Navbar />
      <main>
        <div className={styles.hometext}>
          <h1>Making The Future Sustainable, One Appliance At A Time</h1>
          <p>
            Lorem nisi cupidatat fugiat ullamco voluptate deserunt quis
            cupidatat excepteur labore Lorem eu. Aliquip voluptate pariatur
            incididunt officia esse nisi. Ipsum excepteur consectetur eiusmod
            consectetur sit ipsum dolor.Lorem nisi cupidatat fugiat ullamco voluptate deserunt quis
            cupidatat excepteur labore Lorem eu.
          </p>
          <Link href="/product"><button>Click Me!! ➡</button></Link>
        </div>
        <Image src="/kitten.jpg" alt="placeholder image" width={400} height={400} />
      </main>
    </>
  );
}
